### ISSUE TITLE
Show results index in Number of Results Template

### ISSUE THREAD

**Issue by a30012063** [AddSearch/search-ui#110]
Hello,

Is there a way to show the number of results being shown on the page in the 'Number of results' template

Example right now I see, Showing {{total_hits}}
What we we would like is Showing 10-20 of {{total_hits}}

Thanks in advance

**Comment by haoAddsearch** [comment]
@a30012063 
Hello,

What you need is to create a Handlebars custom helper (let's call it `getRange`) to build the `11-20` part.

```
searchui.registerHandlebarsHelper('getRange', function(page) {
     return `${(page - 1) * 10 + 1} - ${page * 10}`;
});
```

Then use the custom helper in the template, giving the function a single argument `page`.
```
Showing {{getRange page}} of {{total_hits}}
```

`page` is context data retrieved from the API which is passed to the template, search for "Data structure used in searchResults component" in the library's documentation to see other data that API returns and can be used in searchResults component.

Reference:
https://github.com/AddSearch/search-ui?tab=readme-ov-file#register-a-custom-handlebars-helper

**Comment by a30012063** [comment]
Thank you @haoAddsearch
