### ISSUE TITLE
Is search-ui available as ES6 module?

### ISSUE THREAD

**Issue by Lefthandmedia** [AddSearch/search-ui#49]
Hi,

Is search-ui available as ES6 module for import ? if not is there an ETA when this will be available?
tnx
RDG

**Comment by anttiai** [comment]
Hey! The bundle in the _dist_ folder has UMD (Universal Module Definition) as build target, but the library itself is coded in ES6 modules. You add the search-ui source to your project and use ES6 modules directly. An example of this approach is in the [search-ui-react-example](https://github.com/AddSearch/search-ui-react-example/blob/master/src/App.js):

`import AddSearchUI from 'addsearch-search-ui';` 

Does this solve your problem?

**Comment by Lefthandmedia** [comment]
Yep,
maybe worth mentioning this on the github pages.
tnx
