### ISSUE TITLE
Howto filter on publication dates

### ISSUE THREAD

**Issue by Lefthandmedia** [AddSearch/search-ui#50]
Hi,
Each page has an `article:published_time` but how can i make a filter that shows all hits from  only last week or all from just last month. I assumed the range filter would do the trick. But i can't see how.

tnx
RDG

**Comment by anttiai** [comment]
Hi,

The `article:published_time` is [indexed automatically](https://www.addsearch.com/docs/indexing/page-publishing-time/) in a field called `doc_date`. Range filters can contain both start and end boundaries, or just one boundary. Following operators are supported:

- gt (greater than)
- gte (greater than or equal to)
- lt (less than)
- lte (less than or equal to)

The filter for the last 7 days (without end boundary) would be:

```js
{'range': {'doc_date': {'gte': '2021-02-24'}}}
```

A complete example of a radio button group with a few date range options would be:

```js
searchui.filters({
  containerId: 'radio-filters-container',
  type: AddSearchUI.FILTER_TYPE.RADIO_GROUP,
  options: {
    nofilter: {
      label: 'All results'
    },
    thisyear: {
      label: 'This year',
      filter: {'range': {'doc_date': {'gte': '2021-01-01'}}}
    },
    lastyear: {
      label: 'Last year',
      filter: {'range': {'doc_date': {'gte': '2020-01-01', 'lt':'2021-01-01'}}}
    }
  }
});
```
