### ISSUE TITLE
Add custom data to handlebar template?

### ISSUE THREAD

**Issue by Lefthandmedia** [AddSearch/search-ui#52]
Is there a way to add custom data to a handlebar template? I need to this to be able to translate labels in the templates. Suppose i add pagination with
```
  searchui.pagination({
    containerId: 'pagination-container',
    template: MYCUSTOM_PAGINATION_TEMPLATE,
  });
```
but based on the language my page is in i would like the _previous_ button to be 'Previous' but in another language 'Vorige'.
It would be nice then if i can tweak my template this way
```
export const MYCUSTOM_PAGINATION_TEMPLATE = <button data-page="previous" aria-label="Previous page">
      {{data.PREVIOUS}}
      </button>
```
and in in the pagination method pass in a data object

```
  searchui.pagination({
    containerId: 'pagination-container',
    template: MYCUSTOM_PAGINATION_TEMPLATE,
    data: { PREVIOUS: 'Vorige' }
  });
```
This way i would have a lot more control over my templating.
Alternatively you could add a custom data object to the searchui so the custom data would be available to all the UI element. something like `searchui.addCustomData({PREVIOUS: 'Vorige'})`

RDG

**Comment by anttiai** [comment]
That's not supported, but the idea sounds interesting and worth reviewing.

As handlebars templates are just string objects, you could pass the localized texts as you create the template. E.g.:

```js
const i18n = { label: 'hello' };
const template = '<label>' + i18n.label + '</label>';
```

**Comment by Lefthandmedia** [comment]
i fixed it myself  by making the template  a function
`export const MYCUSTOM_PAGINATION_TEMPLATE = ({PREVIOUS}) =><button data-page="previous" aria-label="Previous page">${data.PREVIOUS}</button>;`

and calling the template with a translated parameter

```
  searchui.pagination({
    containerId: 'pagination-container',
    template: MYCUSTOM_PAGINATION_TEMPLATE ({PREVIOUS: lexicon.previous}),
  });
```
The lexicon object is an object with translated strings. i get the correct lexicon based on a language
and it works fine.

RDG
