### ISSUE TITLE
make Totalpages available in pagination

### ISSUE THREAD

**Issue by Lefthandmedia** [AddSearch/search-ui#55]
To show a visitor how many pages the total result contains we would like the total amount of pages to be available in the pagination. 

so we can do something like this
 <previous 1 2 3 4 5 6 ... 12 next>

This can easily be done in pagination.js at #32     
```
const data = {
      currentPage,
      totalPages,
      lastPage: pageArr ? pageArr[pageArr.length-1] : 0,
      pages: pageArr
    };

```
Thanks,
 RDG

**Comment by anttiai** [comment]
Good idea. We'll deploy this improvement early next week.

**Comment by anttiai** [comment]
Added in the [release 0.4.21](https://github.com/AddSearch/search-ui/releases/tag/v0.4.21).
