### ISSUE TITLE
'searchParameter' setting for AddSearchUI constructor not working

### ISSUE THREAD

**Issue by portent-andy** [AddSearch/search-ui#67]
I've tried setting this parameter to something unique, but it doesn't update it. The default "search" URL parameter persists.

**Comment by anttiai** [comment]
Hey, searchParameter seems to works for me. I tested with the latest release (0.5.3).

Could you post an example code that fails? Are you passing the setting to the AddSearchUI constructor? E.g.:

```js
const conf = {
  searchParameter: 'foo'
};
const searchui = new AddSearchUI(client, conf);
```

**Comment by portent-andy** [comment]
I'll test with the latest release. I believe I am using a release from some of your demos, .04.
I was following this demo: https://demo.addsearch.com/search-ui-examples/autocomplete/search.html

`
  var client = new AddSearchClient('XXXX');
  var conf = {
    searchParameter: 'addsearch'
  }
  // Search UI instance
  var searchui = new AddSearchUI(client, conf);
  // Add components
  searchui.searchField({
    containerId: 'searchfield',
    placeholder: 'Search',
    icon: false
  });

  var autocompleteClient = new AddSearchClient('XXXX');
  autocompleteClient.setPaging(1, 7, 'relevance', 'desc'); // Fetch 7 results by default

  var autocompleteTemplate = `
    <div class="addsearch-autocomplete" style="position: relative;">
      {{#gt searchResults.results.length 0}}
      <span class="addsearch-autocomplete__total-results">{{searchResults.results.length}} results</span>
        <ul>
          {{#each ../searchResults.results}}
            <li>
              <strong><a href="{{url}}">{{title}}</a></strong>
            </li>
          {{/each}}
        </ul>
      {{/gt}}
    </div>
  `;

  searchui.autocomplete({
    containerId: 'autocomplete',
    template: autocompleteTemplate,
    infiniteScrollElement: document.querySelector('#scrollable'),
    sources: [
      {
        type: AddSearchUI.AUTOCOMPLETE_TYPE.SEARCH,
        client: autocompleteClient,
        jsonKey: 'results'
      }
    ]
  });

  // All components added. Start
  searchui.start();`

**Comment by portent-andy** [comment]
That looks like the issue. The latest version of the AddSearchUI js (0.5.3) seems to fix the bug. Thanks!

**Comment by anttiai** [comment]
Good to hear, thanks!
