### ISSUE TITLE
Unable to register handlebars partial

### ISSUE THREAD

**Issue by Etroid** [AddSearch/search-ui#72]
Is there a way to register partials so they can be used within some of the addsearch ui templates?

Adding them to the global handlebars using 
```
handlebars.registerPartial('test', '<h1>test</h1>');
```
just results in partial not found errors

**Comment by haoAddsearch** [comment]
Hi Etroid,
New release v0.6.1 now allows registering partials.
Please update your package version to 0.6 and also check README.md on how to use Handlebars partials via AddSearch Search UI Library.
Thank you.
